### ISSUE TITLE
how to scale all page to A4

### ISSUE THREAD

**Issue by retsyo** [pymupdf/PyMuPDF-Optional-Material#23]
I combined some pages from different PDF files, so the pages have various pase size, as a result printed paper looks ugly if I forget to use "fit to paper size". Is there a way to
1. either set every page will be printed on A4 size. In this way, text/vector-drawing on PDF page will still be text/vector-drawing so it still looks clear
2. or zoom the page. 
2.1 But how to make the page looks clear as before?
2.2 I have tried the following code code, it works but I don't like lines
```python
    pix.writePNG('r:/tmp.png')
    img = fitz.open('r:/tmp.png')  # open pic as document
```
so is it possible make it simple?

```python
import fitz
docIn = fitz.open('out - combined.pdf')

docOut = fitz.open()
for idxPage in range(len(docIn)):
    page = docIn[idxPage]

    pix = page.getPixmap()

    pix.writePNG('r:/tmp.png')
    img = fitz.open('r:/tmp.png')  # open pic as document

    rect = img[0].rect  # pic dimension
    pdfbytes = img.convertToPDF()  # make a PDF stream
    img.close()  # no longer needed
    imgPDF = fitz.open("pdf", pdfbytes)  # open stream as PDF
    sizeA4 = fitz.PaperSize("A4")
    page = docOut.newPage(width = sizeA4[0], height = sizeA4[1])
    page.showPDFpage(rect, imgPDF, 0)  # image fills the page

docOut.save("r:/all-my-pics.pdf")
docOut.close()

docIn.close()

```

**Comment by JorjMcKie** [comment]
You alreadyhave walked a promising path.
Assume your source PDF has these page size issues, create a new PDF with A4 pages exckusively from it. Every input page is zoomed automatically to best fit the A4 output page. Then something like this should work.

```python
src = fitz.open("source.pdf")  # problem PDF
doc = fitz.open()
for ipage in src:
    if ipage.rect.width > ipage.rect.height:
        fmt = fitz.PaperRect("a4-l")  # landscape if input suggests
    else:
        fmt = fitz.PaperRect("a4")
    page = doc.newPage(width = fmt.width, height = fmt.height)
    page.showPDFpage(page.rect, src, ipage.number)

doc.save("reformatted.pfd")
```

**Comment by JorjMcKie** [comment]
BTW the above snippet can also be made working for non-PDF input with a few modifications: just convert your input to a PDF first via ``Document.convertToPDF``, then open the result as your source PDF. This is feasible for all supported image formats, XPS, EPUB, etc.

**Comment by kayu100102** [comment]
@JorjMcKie hey, thank you for your answer. I used your approach but my output page are rotated by certain random angles. Please provide a solution to this.

**Comment by JorjMcKie** [comment]
For `page.show_pdf_page(rect, src, pno, ...)` you can also choose a rotation angle for the source page.
So check attributes `.rotation` and `.cropbox` of the source page and choose an adequate `rotate` value for the method.

**Comment by kayu100102** [comment]
source page does not have any rotation. The page is rotated when it is changed

**Comment by JorjMcKie** [comment]
> The page is rotated when it is changed

Changed? By what?

**Comment by dreinon** [comment]
> For `page.show_pdf_page(rect, src, pno, ...)` you can also choose a rotation angle for the source page. So check attributes `.rotation` and `.cropbox` of the source page and choose an adequate `rotate` value for the method.

Hi! The same is happening to me 😅 My approach has been setting the `rotate` argument in `show_pdf_page` to `-ipage.rotation`.
With this, the output file shows a correct orientation, but it is cut, like I show in the screenshots below.
Maybe it has to do with the fact that I'm not using the `.cropbox` in any way, if so, please tell me how could I use it to fix my issue 🙂 

My code snippet:
```py
src = fitz.Document(file)
doc = fitz.Document()
for ipage in src:
    fmt = fitz.paper_rect("a5-l")  #All pages have to be set horizontally
    page = doc.new_page(width=fmt.width, height=fmt.height)
    page.show_pdf_page(page.rect, src, ipage.number, rotate=-ipage.rotation)
src.close()
doc.save(file.parent/f"{file.stem}_resized.pdf")
```
Original file (output should look alike but have the proper size):
![image](https://user-images.githubusercontent.com/67071425/155233604-8f5648e5-890f-4b30-9c12-6a1c87971e41.png)

Output file:
![image](https://user-images.githubusercontent.com/67071425/155233744-ec99f112-7815-4384-b4ef-f835a8eee138.png)

Thanks!

**Comment by dreinon** [comment]
This has worked for me, but I find it a bit hacky:
```py
src = fitz.Document(file)
doc = fitz.Document()
for ipage in src:
    rotation = ipage.rotation
    if rotation in {90, 270}:
        fmt = fitz.paper_rect("a5")
        ipage.set_rotation(0)
    else:
        fmt = fitz.paper_rect("a5-l")
    page = doc.new_page(width=fmt.width, height=fmt.height)
    page.show_pdf_page(page.rect, src, ipage.number)
    page.set_rotation(rotation)
src.close()
doc.save(file.parent/f"{file.stem}_resized.pdf")
```

**Comment by JorjMcKie** [comment]
@dreinon - well, I think you found a good solution.
The thought behind this is a good one: de-rotate the source, then put it in the target page, then rotate the target page as was the source.

**Comment by Abdel4145** [comment]
Hello every one, 
Is very nice job, 
I have two issues : 
     is it possible to scall to tabloid format (11inch *17inch )  or 432 mm * 279 mm?
     how can i use this function to a list of pdf files with for loop?

Many thanks
